/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoutingRouteImport } from './routes/routing'
import { Route as PaletteRouteImport } from './routes/palette'
import { Route as LayoutRouteImport } from './routes/layout'
import { Route as IntersectionRouteImport } from './routes/intersection'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as EditableRouteImport } from './routes/editable'
import { Route as CollabRouteImport } from './routes/collab'
import { Route as IndexRouteImport } from './routes/index'

const RoutingRoute = RoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaletteRoute = PaletteRouteImport.update({
  id: '/palette',
  path: '/palette',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IntersectionRoute = IntersectionRouteImport.update({
  id: '/intersection',
  path: '/intersection',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const EditableRoute = EditableRouteImport.update({
  id: '/editable',
  path: '/editable',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabRoute = CollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collab': typeof CollabRoute
  '/editable': typeof EditableRoute
  '/flow': typeof FlowRoute
  '/intersection': typeof IntersectionRoute
  '/layout': typeof LayoutRoute
  '/palette': typeof PaletteRoute
  '/routing': typeof RoutingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collab': typeof CollabRoute
  '/editable': typeof EditableRoute
  '/flow': typeof FlowRoute
  '/intersection': typeof IntersectionRoute
  '/layout': typeof LayoutRoute
  '/palette': typeof PaletteRoute
  '/routing': typeof RoutingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collab': typeof CollabRoute
  '/editable': typeof EditableRoute
  '/flow': typeof FlowRoute
  '/intersection': typeof IntersectionRoute
  '/layout': typeof LayoutRoute
  '/palette': typeof PaletteRoute
  '/routing': typeof RoutingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collab'
    | '/editable'
    | '/flow'
    | '/intersection'
    | '/layout'
    | '/palette'
    | '/routing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collab'
    | '/editable'
    | '/flow'
    | '/intersection'
    | '/layout'
    | '/palette'
    | '/routing'
  id:
    | '__root__'
    | '/'
    | '/collab'
    | '/editable'
    | '/flow'
    | '/intersection'
    | '/layout'
    | '/palette'
    | '/routing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollabRoute: typeof CollabRoute
  EditableRoute: typeof EditableRoute
  FlowRoute: typeof FlowRoute
  IntersectionRoute: typeof IntersectionRoute
  LayoutRoute: typeof LayoutRoute
  PaletteRoute: typeof PaletteRoute
  RoutingRoute: typeof RoutingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/routing': {
      id: '/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof RoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palette': {
      id: '/palette'
      path: '/palette'
      fullPath: '/palette'
      preLoaderRoute: typeof PaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intersection': {
      id: '/intersection'
      path: '/intersection'
      fullPath: '/intersection'
      preLoaderRoute: typeof IntersectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editable': {
      id: '/editable'
      path: '/editable'
      fullPath: '/editable'
      preLoaderRoute: typeof EditableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab': {
      id: '/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof CollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollabRoute: CollabRoute,
  EditableRoute: EditableRoute,
  FlowRoute: FlowRoute,
  IntersectionRoute: IntersectionRoute,
  LayoutRoute: LayoutRoute,
  PaletteRoute: PaletteRoute,
  RoutingRoute: RoutingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
